live_config_reload = true

import = [
  "/Users/rakesh/.config/alacritty/catppuccin-macchiato.toml"
]

[font]
size = 15.0

[cursor]
style= { blinking = "Never"}

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[window]
decorations = "buttonless"
dynamic_padding = false
# opacity = 0.95
blur = true
option_as_alt = "both"
startup_mode = "Maximized"
decorations_theme_variant = "Dark"


[window.padding]
x = 3
y = 2

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "Key6", mods = "Control", chars = "\u001e" }
]
