#!/bin/bash

if [ "$PWD" = "$HOME" ]; then
	file=$({
		find -L ~ -mindepth 1 -maxdepth 4 -type f ! -name "." ! -name '*.DS_Store' ! -path "*/.Trash/*" ! -path "*/.vim/*" ! -path "*/.vscode/*" ! -path "*/.git/*" ! -path "*/.tmux/*" ! -path "*/Library/*" ! -path "*/.cache/*" ! -path "*/.npm/*" ! -path "*/Pictures/*" ! -path "*/Movies/*" ! -path "*/Music/*" ! -path "*/mypy_cache/*" -print
		find -L ~/dotfiles -type f ! -name '*.DS_Store' ! -path "*/.git/*"
	} | sed 's|^\./||' | fzf --prompt "   " --pointer "󰁕" --height=80% --reverse --preview 'bat {}')
else
	file=$(find -L . -type f -not -path '*/.git/*' ! -name '*.DS_Store' | sed 's|^\./||' | fzf --prompt "   " --pointer "󰁕" --height=80% --reverse --preview 'bat {}')
fi

if [ -n "$file" ]; then
	extension="${file##*.}"

	if [ "$extension" == "jpeg" ] || [ "$extension" == "jpg" ] || [ "$extension" == "png" ] || [ "$extension" == "pdf" ] || [ "$extension" == "pptx" ] || [ "$extension" == "ppt" ] || [ "$extension" == "doc" ]; then
		open "$file"
	else
		nvim "$file"
	fi
else
	echo "No file selected"
fi
