#!/bin/bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(find ~/Documents/* ~/ -mindepth 1 -maxdepth 4 -type d ! -name "." ! -path "*/.Trash/*" ! -path "*/.vscode/*" ! -path "*/.git/*" ! -path "*/Library/*" ! -path "*/.cache/*" ! -path "*/.npm/*" ! -path "*/Pictures/*" ! -path "*/Movies/*" ! -path "*/Music/*" 2>/dev/null | fzf --reverse --prompt "   " --pointer "󰁕" --preview 'tree -C {}')
fi

if [[ -z $selected ]]; then
	echo "No directory selected."
	exit 1
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s "$selected_name" -c "$selected"
	exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
	tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -n $TMUX ]]; then
	tmux switch-client -t "$selected_name"
elif [[ -n $tmux_running ]]; then
	tmux attach-session -t "$selected_name"
else
	echo "No tmux session found."
fi
