unbind r
bind r source-file ~/.tmux.conf

# act like vim
setw -g mode-keys vi
bind -r ^ last-window
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

#to open split in same directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -s escape-time 0

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

#Dracula theam
#set -g @plugin 'dracula/tmux'
#set -g @dracula-show-powerline true
#set -g @dracula-military-time true
#set -g @dracula-day-month true
#set -g @dracula-show-timezone false
#set -g @dracula-plugins "time"
#set -g @dracula-show-flags true
#set -g @dracula-show-left-icon session

#Gruvbox theam
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark' # or 'light'

set -g status-position top
set-option -g focus-events on


# for tmux-sessionizer
bind-key -r f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
