unbind r
bind r source-file ~/.tmux.conf

# act like vim
setw -g mode-keys vi
bind -r ^ last-window
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

#to open split in same directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -s escape-time 0

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

#Gruvbox theam
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark' # or 'light'

set -g status-position top
set-option -g focus-events on
set-option -g detach-on-destroy off


# for tmux-sessionizer
bind-key -n '^f' run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"
bind-key -r '^ ' run-shell "tmux neww ~/.local/scripts/tmux-sessionizer ~/"
bind -r C-k display-popup -E "\
    tmux list-sessions -F '#{?session_attached,,#{session_name}}' |\
    sed '/^$/d' |\
    fzf --reverse --header jump-to-session --preview 'tmux capture-pane -pt {}'  |\
    xargs tmux switch-client -t"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
