#!/bin/bash

if [ "$PWD" = "$HOME" ]; then
    file=$(find ~ -mindepth 1 -maxdepth 3 \( -path ~/Library -o -path ~/.Trash \) -prune -o -type f ! -name '*.DS_Store'  -print | fzf --height=80% --reverse --preview 'bat {}')
else
    file=$(find . -type f | fzf --height=80% --reverse --preview 'bat {}')
fi

if [ -n "$file" ]; then
    nvim "$file"
else
  echo "No file selected"
fi
